# Generated by Django 6.1 on 2026-08-25 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.AddField(
            model_name='company',
            name='has_phone_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='price_markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.company'),
        ),
        migrations.CreateModel(
            name='CompanyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('price_markup', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_rules', to='core.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_rules', to='core.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'product'), name='unique_company_product')],
            },
        ),
    ]
