# Generated by Django 6.1 on 2026-08-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_comment_order_ordered_by_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='companyproduct',
            name='unique_company_product',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Företag', 'verbose_name_plural': 'Företag'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Ordrar'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Orderrad', 'verbose_name_plural': 'Orderrader'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkter'},
        ),
        migrations.AddField(
            model_name='company',
            name='allowed_phones',
            field=models.ManyToManyField(blank=True, limit_choices_to={'product_type': 'phone'}, related_name='allowed_for_companies', to='core.product'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(db_index=True, help_text='Nyckeln kunden loggar in med.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Väntar'), ('processing', 'Behandlas'), ('completed', 'Slutförd'), ('cancelled', 'Avbruten')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('phone', 'Telefon'), ('accessory', 'Tillbehör')], db_index=True, default='phone', max_length=20),
        ),
        migrations.RemoveField(
            model_name='companyproduct',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='CompanyUser',
        ),
        migrations.DeleteModel(
            name='CompanyProduct',
        ),
    ]
