# Generated by Django 6.1 on 2026-08-27 12:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_companyproduct_unique_company_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ditt grundläggande utpris (t.ex. inköp x 0.8).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='price_markup',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Procentuellt påslag för företaget (t.ex. 10.00 för +10%).', max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Inköps-/feedpris från leverantören.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
