# Generated by Django 6.1 on 2026-08-27 13:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_price_alter_company_price_markup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='allowed_phones',
            field=models.ManyToManyField(blank=True, related_name='allowed_for_companies', to='core.product', verbose_name='Valt sortiment (telefoner & tillbehör)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='has_phone_policy',
            field=models.BooleanField(default=False, help_text='Om aktiv visas endast de produkter som valts nedan.', verbose_name='Har sortimentspolicy'),
        ),
        migrations.AlterField(
            model_name='company',
            name='price_markup',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fast påslag i kronor (SEK) per produkt (t.ex. 250.00).', max_digits=10),
        ),
    ]
