# Generated by Django 6.1 on 2026-09-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_company_allowed_phones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, help_text='E-postadress som används för orderbekräftelser.', max_length=254, verbose_name='E-post'),
        ),
    ]
