# Generated by Django 6.1 on 2026-09-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_class',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Prisklass 1 – 99 kr'), (2, 'Prisklass 2 – 149 kr'), (3, 'Prisklass 3 – 249 kr')], null=True, verbose_name='Prisklass'),
        ),
    ]
