# Generated by Django 6.1 on 2026-09-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_price_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feed_category',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Feedkategori'),
        ),
        migrations.AddField(
            model_name='product',
            name='feed_product_type',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Feed product type'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_family',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Modellfamilj'),
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_mode',
            field=models.CharField(choices=[('auto', 'Automatiskt från feed'), ('manual', 'Manuellt pris')], db_index=True, default='auto', max_length=10, verbose_name='Prissättning'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_category',
            field=models.CharField(blank=True, choices=[('phone', 'Telefon'), ('case', 'Skal & fodral'), ('screen_protector', 'Skärmskydd'), ('charger', 'Laddare'), ('cable', 'Kablar'), ('powerbank', 'Powerbanks')], db_index=True, default='', max_length=30, verbose_name='Webshopkategori'),
        ),
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(choices=[('manual', 'Manuell'), ('telefonshoppen', 'Telefonshoppen')], db_index=True, default='manual', max_length=50, verbose_name='Källa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Lagerstatus'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Inköps-/feedpris från leverantören.', max_digits=10, verbose_name='Feedpris'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Varumärke'),
        ),
        migrations.AlterField(
            model_name='product',
            name='external_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Externt ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='mpn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Produktnamn'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Grundpris före företagets kundspecifika påslag.', max_digits=10, null=True, verbose_name='Compartners grundpris'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_class',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Prisklass 1 – 99 kr'), (2, 'Prisklass 2 – 149 kr'), (3, 'Prisklass 3 – 249 kr')], db_index=True, null=True, verbose_name='Prisklass'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('phone', 'Telefon'), ('accessory', 'Tillbehör')], db_index=True, default='phone', max_length=20, verbose_name='Produkttyp'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', 'product_type'], name='product_active_type_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', 'shop_category'], name='product_active_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'model_family'], name='product_brand_model_idx'),
        ),
    ]
