# Generated by Django 6.1 on 2026-09-21 07:10

import django.core.validators
import django.db.models.deletion

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0009_product_feed_category_product_feed_product_type_and_more",
        ),
    ]

    operations = [
        # =====================================================
        # 1. SKAPA NY PRICECLASS-MODELL
        # =====================================================

        migrations.CreateModel(
            name="PriceClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text=(
                            "Exempel: Laddare avtal, Skal standard, "
                            "Premiumtillbehör."
                        ),
                        max_length=100,
                        unique=True,
                        verbose_name="Namn",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        verbose_name="Beskrivning",
                    ),
                ),
                (
                    "cost_mode",
                    models.CharField(
                        choices=[
                            ("feed", "Använd feedpris"),
                            ("fixed", "Fast inköpspris"),
                            ("discount", "Rabatt från feedpris"),
                        ],
                        default="feed",
                        max_length=20,
                        verbose_name="Inköpsmodell",
                    ),
                ),
                (
                    "cost_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text=(
                            "Vid fast inköpspris anges kronor. "
                            "Vid rabatt anges procent, "
                            "t.ex. 35 för 35 % rabatt."
                        ),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00")
                            )
                        ],
                        verbose_name="Inköpsvärde",
                    ),
                ),
                (
                    "price_mode",
                    models.CharField(
                        choices=[
                            (
                                "fixed_markup",
                                "Fast påslag i kronor",
                            ),
                            (
                                "percentage",
                                "Procentpåslag",
                            ),
                            (
                                "fixed_price",
                                "Fast utpris",
                            ),
                        ],
                        default="fixed_markup",
                        max_length=20,
                        verbose_name="Försäljningsmodell",
                    ),
                ),
                (
                    "price_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text=(
                            "Vid fast påslag anges kronor. "
                            "Vid procentpåslag anges procent. "
                            "Vid fast utpris anges slutpriset."
                        ),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00")
                            )
                        ],
                        verbose_name="Prisvärde",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Aktiv",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=100,
                        verbose_name="Sortering",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prisklass",
                "verbose_name_plural": "Prisklasser",
                "ordering": [
                    "sort_order",
                    "name",
                ],
            },
        ),

        # =====================================================
        # 2. UPPDATERA BEFINTLIGA PRISFÄLT
        # =====================================================

        migrations.AlterField(
            model_name="product",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text=(
                    "Priset från Telefonshoppens feed. "
                    "Det behöver inte vara Compartners "
                    "verkliga inköpspris."
                ),
                max_digits=10,
                verbose_name="Feedpris",
            ),
        ),

        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text=(
                    "Grundpris före företagets kundspecifika "
                    "påslag. Vid automatisk prissättning "
                    "räknas detta fram från vald prisklass."
                ),
                max_digits=10,
                null=True,
                verbose_name="Compartners grundpris",
            ),
        ),

        migrations.AlterField(
            model_name="product",
            name="pricing_mode",
            field=models.CharField(
                choices=[
                    (
                        "auto",
                        "Automatisk prissättning",
                    ),
                    (
                        "manual",
                        "Manuellt pris",
                    ),
                ],
                db_index=True,
                default="auto",
                max_length=10,
                verbose_name="Prissättning",
            ),
        ),

        # =====================================================
        # 3. DÖP OM GAMLA INTEGER-FÄLTET
        #
        # price_class innehåller idag 1 / 2 / 3.
        # Vi får INTE konvertera dessa värden direkt till FK.
        # =====================================================

        migrations.RenameField(
            model_name="product",
            old_name="price_class",
            new_name="old_price_class",
        ),

        # =====================================================
        # 4. SKAPA ETT HELT NYTT price_class-FÄLT SOM FK
        #
        # Alla befintliga produkter börjar med NULL.
        # =====================================================

        migrations.AddField(
            model_name="product",
            name="price_class",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Prisklassen bestämmer verklig "
                    "inköpskostnad och automatiskt utpris."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="core.priceclass",
                verbose_name="Prisklass",
            ),
        ),

        # =====================================================
        # 5. TA BORT GAMLA PRISKLASSEN 1 / 2 / 3
        #
        # Vi behöver inte migrera dessa eftersom den nya
        # PriceClass-modellen har en helt annan betydelse.
        # =====================================================

        migrations.RemoveField(
            model_name="product",
            name="old_price_class",
        ),
    ]